server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://alarmcrew-db.c2fovbmhnzav.ap-northeast-2.rds.amazonaws.com:3306/alarmcrew?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: kansiro0314
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB

jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

cloud:
  aws:
    region:
      static: ap-northeast-2
    #    s3:
    #      bucket: ouruniversebucket
    stack:
      auto: false
